### ISSUE TITLE
Hello EDGI!

### ISSUE THREAD

**Issue by osterbit** [edgi-govdata-archiving/eis-search#2]
Just wanted to introduce myself--I'm Tom, I work at QRI and made this initial pass at a searchable EIS database tool.  

It is definitely a work in progress and would be very appreciative of any issue submissions (or PRs) to help direct continued development of this and the improvement of related tools.

I also wanted to note that the original directive for this tool was to build a python flask app with elasticsearch but I ended up using golang and bleve instead because it allowed the app to be hosted on a single server for free (on heroku) with the index being portable as a static database (rather than needing an additional elasticsearch server).

**Comment by lightandluck** [comment]
Hi, Tom! I'm Kevin and I help out on the Web Monitoring project. This is really awesome! For anyone wanting to take a quick peek, there's a [demo](http://eis-search.herokuapp.com/).

**Comment by shapironick** [comment]
This is so great! thanks, tom!

I'm planning on sending a letter off to our Columbia environmental lawyer collaborator for initial impressions. More word soon and thanks!

**Comment by titaniumbones** [comment]
wow, that was really cool, Tom! I just finally looked at this.  Thank you!

**Comment by shapironick** [comment]
Feedback from Columbia was very brief but positive. They could already see how useful a full tool would be. So we have the user support now to confidently keep working and will ask them for feature requests soon.
