### ISSUE TITLE
License for this repo?

### ISSUE THREAD

**Issue by Frijol** [edgi-govdata-archiving/eis-search#20]
Work is all rights reserved unless otherwise specified; I think we want to specify a more open license for this work. I would suggest CC0, MIT, or Apache 2.0 (CC0 as my initial inclination).

Thoughts @b5 @Mr0grog @lightandluck @osterbit?

**Comment by lightandluck** [comment]
I have no idea, sorry!

**Comment by Mr0grog** [comment]
It should be GPL v3: https://github.com/edgi-govdata-archiving/overview/blob/master/repo_guidelines.md#about-the-license :)

**Comment by Frijol** [comment]
oh excellent! I'll PR it onto the repo.
