### ISSUE TITLE
Cost Scoping

### ISSUE THREAD

**Issue by shapironick** [edgi-govdata-archiving/eis-search#3]
We said we would scope costs in a gh issue. Lets do that here

**Comment by b5** [comment]
Getting a feel for the current costs, we made a few tech choices that make this demo quite cheap to host. 
### Key tech choices:
* demo to fits inside "one box". we made sure the app would work on heroku's free tier
* **not hosting any data**. Currently the search index just links to other places that bear storage costs
* reduced dev time thanks to using tech a few of us are already familiar with

### Demo Costs:
* https://eis-search.herokuapp.com is currently free
* realistic cost to host this demo would be $14/month if the app were to have real traffic 

We have more work to do in properly scoping costs of any "upgrades", but I wanted to get the note out on current ops costs, and point to the "levers" that can trigger cost increases: dev time, storage, ops infrastructure

**Comment by titaniumbones** [comment]
Probably I should spin up a second issue for this, but I would also like to think about a different level of cost assessment. Like, what would it cost (in $$, but also thinking about time spent not-working-on-other-things) to implement some of the various improvements discussed in #7? Don't think we're quite ready to add numbers but when we're ready to do so perhaps we should.
