### ISSUE TITLE
Add build/run instructions

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/eis-search#8]
steps to clone/build/run on localhost are probably obvious to go people but I'm having some trouble doing this is a non-go person.  Would love to see the instructions in the README so illiterates like myself can try running locally & adidng e.g. extra HTML to make some things obvious to potential users/ testers.

**Comment by Frijol** [comment]
+1 and as an open source org we should adopt documentation practices as part of development flow! Needs to support new contributors as well as be flexible to participants who drop in/out as their availability changes

**Comment by Frijol** [comment]
Figured it out!

Prereq for doing anything:

1. Install [Go](https://golang.org/dl/), and make sure your GOPATH ends up in the right PATH profile (there are a lot of tutorials around for this)

To just run locally:

2. Install this repo's dependencies with `go get github.com/edgi-govdata-archiving/eis-search`, (run this from any directory)
3. This actually builds it too, so if you just `cd` into `$HOME/go/bin`, you can run `./eis-search` and it will serve up at http://localhost:8094

To clone & modify (not dependent on the "just running" instructions above):

2. Clone this repo into your go directory (`$HOME/go/src` ordinarily. `go get` put dependencies in `$HOME/go/bin` for you).
1. Build the project. From inside that cloned directory, `go build`. This should make a file called `eis-search`
1. Run: `./eis-search`. Go see it at http://localhost:8094

The main Go newbie gotcha, as far as I can tell:
* Go is set up to all run from a particular Go directory on your computer, default `$HOME/go`. You're supposed to do all your Go work within that folder
